# Generated by Django 5.0.6 on 2024-07-08 19:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='exp_date',
            field=models.DateField(default=datetime.date(2024, 1, 1)),
        ),
    ]
