# Generated by Django 5.0.6 on 2024-07-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_exp_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_expired',
            field=models.BooleanField(default=True),
        ),
    ]
