# Generated by Django 5.0.6 on 2024-07-09 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_file', models.FileField(upload_to='videos/')),
                ('placeholder_image', models.ImageField(upload_to='images/')),
                ('title', models.CharField(max_length=30)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Horror', 'Horror'), ('Romance', 'Romance'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Science Fiction (Sci-Fi)'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('Crime', 'Crime'), ('Historical', 'Historical'), ('Musical', 'Musical'), ('Documentary', 'Documentary'), ('Animated', 'Animated'), ('Western', 'Western'), ('War', 'War')], max_length=20)),
                ('description', models.CharField(max_length=250)),
                ('duration', models.CharField(max_length=5)),
                ('cast', models.CharField(max_length=250)),
            ],
        ),
    ]
