# Generated by Django 5.0.6 on 2024-07-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_video_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='year',
            field=models.IntegerField(default=2024),
        ),
    ]
